Ops 5155 evaluate triggering awx from GitHub (#76)
* OPS-5155 Minimal Github workflow to trigger AWX

* OPS-5155 Forgot secrets.

* OPS-5155 Forgot TOWER_HOST env

* OPS-5155 Removed extra period in AWX version

* OPS-5155 Only keep AWX job url and status

* OPS-5155 Moved output filtering to AWX command

* OPS-5155 Pip install jq

* OPS-5155 Add detail field to output

* OPS-5155 Switch back to using jq outside the awx command

diff --git a/.github/workflows/trigger-awx.yaml b/.github/workflows/trigger-awx.yaml
--- a/.github/workflows/trigger-awx.yaml
+++ b/.github/workflows/trigger-awx.yaml
@@ -31,7 +31,7 @@ jobs:
   run_awx:
     runs-on: ubuntu-latest
     steps:
-      - name: Install awxkit
+      - name: Pip install awxkit
         run: |
           pip3 install awxkit==${{ inputs.awxkit_version }}
       - name: Run the job
@@ -39,4 +39,8 @@ jobs:
           TOWER_HOST: ${{ inputs.host }}
           TOWER_OAUTH_TOKEN: ${{ secrets.AWX_TOKEN }}
         run: |
-          awx job_template launch ${{ inputs.job_id }} --job_type ${{ inputs.job_type }} --wait --interval 10
+          # Needed to keep the exit code of the AWX command after piping the output to jq
+          set -o pipefail
+          # Only keep job URL, job status and detail which contains error messages
+          # We don't use the awx jq output format because it doesn't show error messages
+          awx job_template launch ${{ inputs.job_id }} --job_type ${{ inputs.job_type }} --wait --interval 10 | jq '{"url": "https://awx.dbildungscloud.de/#/jobs/\(.job)", "status": .status, "detail": .detail }'
